// TRACK SETTINGS
TRACK_LENGTH = 20;
TRACK_MAX_ANGLE_DEG = 45;
TRACK_MAX_ANGLE_CHANGE_DEG = 90;
PLATFORM_LENGTH = 2;
START_PLATFORM_LENGTH = 3;
STOP_PLATFORM_LENGTH = PLATFORM_LENGTH * 2;

// CAR SETTINGS
WHEEL_SPEED = 30;
START_POSITION = [1.7, 0.7];
VERTICY_BOUNDS = [4, 12];
CHASSIS_DENSITY = 2;

// GAME WORLD SETTINGS
MAX_ANGLE_STEP_FRAC=8;
MAX_LENGTH_STEP_FRAC=5;
MAX_WHEEL_STEP_FRAC=5;
GENERATIONS_TO_SAVE_CSV = 1000;
CAR_STUCK_TOL = 0.1;  // difference of the last and current positions
CAR_STUCK_CHECK_INTERVAL = 1000;  // in msecs
MAX_SKIP_NUM = 1000;  // maximum number of skip number in UI
FRICTION = 3;

// ES SETTINGS
START_POP_SIZE = 30;
MU = START_POP_SIZE;
LAMBDA = Math.floor(MU / 2);
LENGTH_BOUNDS = [0.2, 1];
CHANGE_NUMVERTICIES_PROBABILITY = 0.05;
ANGLE_BOUNDS = [Math.PI / 8, Math.PI * (3/8)];
